# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:Fv4xgWMTJ+XuQTXR/EtEcZJldWjZ4c1s7FQQMuzMpIXSRhEfDA==,iv:BVM51M7dFCTeQetAJgVQigh5YHJjfyUMy05rS5kORbs=,tag:evkmHJ07Pewu6gfibMCJvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYnpSNCtLclhrRFgwVzdu
            TjhQNjJvNXcvbzcxaDgyUUtUNWRFbW92TUVNCkR1Z2hlQmErdWNwdkpWZzA4czZy
            UmhiRUV5ZlU0RlhUSWRDaVE3S0tINWcKLS0tIGdCM3VQaWFOTHBEelFYS0t4QnUy
            TFVjM1BEcVJrVkFGSmdKS2ZLYmswZ1kKMgqXZm+Om3Fhh98uelakRfPTiUrGHV1R
            t4HRTqRsEUwYzUr/cDFj3wS3stdFZv65F8PVU6giEvk9Qp7zArI8uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-25T18:23:49Z"
    mac: ENC[AES256_GCM,data:IYPedOegYSqinDky5gMntu420m7m3XaVGMXzl/IXWm+zlhV+uJfoNOUxbs+pdHPkXAZBIZRkED6UVR5znzFMD7ueqPQ+DQJVIzCF7BGzUiNrlmwH69b9cUmyoHEBE4ZiCeaaiYUHntAmwOO+3sosnQXJ0EuM5FRZb6mObPLNGd8=,iv:AjQa1CnKjXvEudvtL2Jzecu3RcQSRreG6ndEg3LHMdY=,tag:Z8SKdtYdzmV/MCnlG2hy5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
