---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Toronto
  METALLB_LB_RANGE: 199.85.99.18-199.85.99.27
  METALLB_K8S_GATEWAY_ADDR: 199.85.99.27
  METALLB_TRAEFIK_ADDR: 199.85.99.20
