# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:CId4q9qDLo9OFTf+CVjDlD8Jx+WtGnIqIz1IBMmDKDj18rpRt2ayxQ==,iv:zkNBYAVlGE6nbzYtpLrwBt8SYAax3NbqLM7BlMClr9U=,tag:MTr6VN/p7U8vjCVZ6eaKXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWHVYRjFsMEZYbDlmUm9v
            NWFGdTFkWWlNVVlTcmtKdnFJM202YmhGVFZVCjR2M2x2YVY3dE0xVWhCM2lwYmQw
            Wi9YaURnNkN6cjlYaEgzQTR1OWRubFUKLS0tIFc5aGZoOGh1NUd6MnBER2JyL0t3
            d200RVprNnZBdEplVXhiWXpadU1BbGcKubQhIADyFFjBubmkUyod3ahhqIG/SJjj
            OeXLIX1i6e+6fc5YX69dRYvRabzOAnCwxfJQF/WhOSunftoLsG++zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-25T18:23:50Z"
    mac: ENC[AES256_GCM,data:N/d9gnnWKweyT1+JC31q0y0MCgkbWdcAuMMI4/7Kfr/HoEijvg7oXj0evWgD8UfySntQVGKX5puRSuXewtDQbiWU5pn2xnZSp78voka91ynEgZNC3P4PV3d5/9qNhWVWBSeV53G1otT5Dj3bPjKVkhoE2FAyWH0yff14Lxeh7gU=,iv:zx7/q0hCsZWCcIoDMoi/x7xVKDPF0OsfI04MUdIF1E0=,tag:Z1sxwICu/QpY79Y+k82fXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
